services:
  - type: web
    name: rwanda-edu-backend
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app.main:app
    envVars:
      - key: DATABASE_URL
        scope: build,runtime
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ENVIRONMENT
        value: production
